name: Deploy MapQuester Backend to AWS Elastic Beanstalk

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  deploy:
    name: Deploy MapQuester Backend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    - name: Install EB CLI
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli
    
    - name: Extract and Sanitize Version
      id: get_version
      run: |
        # Extract version, remove 'refs/tags/v' prefix, and sanitize
        RAW_VERSION="${GITHUB_REF#refs/tags/v}"
        # Remove any characters that might cause issues
        CLEAN_VERSION=$(echo "$RAW_VERSION" | sed 's/[^a-zA-Z0-9.-]/_/g')
        echo "VERSION=$CLEAN_VERSION" >> $GITHUB_OUTPUT
        echo "Cleaned version: $CLEAN_VERSION"
    
    - name: Prepare Backend Deployment Package
      run: |
        cd mapquester_backend
        zip -r ../deploy.zip . -x '.git*' -x '.github*'
        cd ..
    
    - name: Deploy to Elastic Beanstalk
      env:
        EB_APPLICATION: mapquester-backend
        EB_ENVIRONMENT: MapquesterBackend-env
        DEPLOY_VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: |
        cd mapquester_backend
        
        # Create a deployment-friendly version label
        LABEL=$(echo "$DEPLOY_VERSION" | cut -c1-100)
        
        eb init -r us-west-2 -p python-3.10 $EB_APPLICATION
        eb use $EB_ENVIRONMENT
        
        # Deploy with a clean version label
        eb deploy $EB_ENVIRONMENT --label "$LABEL"
    
    - name: Deployment Notification
      if: success()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Deployment of MapQuester Backend to Elastic Beanstalk successful! 🚀
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}